#!/usr/bin/env bash
rm -rf public && npx antora --fetch antora-playbook.yml
cp css/*.css public/_/css/
cp -r public/* /var/www/familienkunde.com/menzingen/
cp -r public/_ /var/www/familienkunde.com/menzingen/
